# Configuracion Spring Native
spring.aot.enabled=true
spring.native.remove-unused-autoconfig=true
spring.native.remove-yaml-support=false

# Virtual Threads (Java 21)
#spring.threads.virtual.enabled=true

# Optimizaciones de memoria
spring.jmx.enabled=false
management.endpoints.web.exposure.include=health,info

# Configuracion de logging
logging.level.org.springframework=INFO
logging.level.org.graalvm=DEBUG

# Server configuration
#server.port=8080
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# Configuracion de seguridad b�sica
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false
