# .github/workflows/build-native-arm64.yml
name: Build Spring Boot Native ARM64

on:
  # Ejecutar en push a main/master
  #push:
  #  branches: [ main, master ]
  #  paths-ignore:
  #    - 'README.md'
  #    - 'docs/**'
  
  # Ejecutar en pull requests
  #pull_request:
  #  branches: [ main, master ]
  
  # Permitir ejecución manual
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests during build'
        required: false
        default: 'false'
        type: boolean

jobs:
  build-arm64:
    runs-on: ubuntu-24.04-arm      # runner ARM64
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'

      - name: Build native (AOT)
        #run: mvn -Pnative -DskipTests -Dspring.aot.enabled=true -B package
        run: mvn -Pnative -DskipTests -Dspring.aot.enabled=true -B native:compile

      - name: Upload native artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipool-linux-aarch64
          path: target/pipool