# .github/workflows/build-native-arm64.yml
name: Build Spring Boot Native ARM64

on:
  # Ejecutar en push a main/master
  #push:
  #  branches: [ main, master ]
  #  paths-ignore:
  #    - 'README.md'
  #    - 'docs/**'
  
  # Ejecutar en pull requests
  #pull_request:
  #  branches: [ main, master ]
  
  # Permitir ejecución manual
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip tests during build'
        required: false
        default: 'false'
        type: boolean

jobs:
  build-arm64:
    runs-on: ubuntu-24.04-arm   # runner ARM64
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          components: 'native-image'

      - name: Build native (AOT)
        run: mvn -Pnative -DskipTests -Dspring.aot.enabled=true -B package
          
      - uses: actions/upload-artifact@v4
        with:
          name: pipool-linux-aarch64
          path: |
            target/pipool