# .github/workflows/deploy-to-prod.yml
name: Deploy to Production

#on:
  # workflow_dispatch:
  #   inputs:
  #     artifact_name:
  #       description: 'Artifact name to deploy'
  #       required: true
  #       default: 'pipool-linux-aarch64'

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}
          path: .

      - name: List Downloaded Files
        run: ls -lh

      - name: Deploy to Production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PROD_HOST: ${{ secrets.PROD_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          # 1. Conexión y parada del servicio
          ssh -i <(echo "$SSH_PRIVATE_KEY") -o StrictHostKeyChecking=no $SSH_USER@$PROD_HOST "sudo systemctl stop pipool"
          
          # 2. Respaldo del ejecutable antiguo
          ssh -i <(echo "$SSH_PRIVATE_KEY") -o StrictHostKeyChecking=no $SSH_USER@$PROD_HOST "sudo mv /home/pi/pipool/pipool /home/pi/pipool/pipool_backup_$(date +%Y%m%d%H%M%S)"

          # 3. Copia del nuevo ejecutable
          scp -i <(echo "$SSH_PRIVATE_KEY") -o StrictHostKeyChecking=no target/pipool $SSH_USER@$PROD_HOST:/home/pi/pipool/pipool
          
          # 4. Iniciar el nuevo servicio
          ssh -i <(echo "$SSH_PRIVATE_KEY") -o StrictHostKeyChecking=no $SSH_USER@$PROD_HOST "sudo systemctl start pipool"

          # 5. Confirmación del despliegue con ping a /ping
          APP_HOST_URL="https://${{ env.PROD_HOST }}:8045/pipool/api/v1/rpistate/ping" # Ajusta el puerto si es necesario
          echo "Pinging ${APP_HOST_URL} ..."
          for i in {1..10}; do
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${APP_HOST_URL})
            if [ "$HTTP_STATUS" == "200" ]; then
              echo "Application is up and running!"
              exit 0
            fi
            echo "Waiting for the application to start... (Attempt $i/10)"
            sleep 10  
          done
          echo "Application failed to start after multiple attempts."
          exit 1
